version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml

  prism:
    image: stoplight/prism:latest
    command: --cors -p 3000 -h 0.0.0.0 mock /data
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./swagger.yaml
        target: /data


